import 'package:flutter/material.dart';
import 'package:ottaa_theme/src/theme/ottaa_colors.dart';

ThemeData kOttaaLightThemeData = ThemeData(
  brightness: Brightness.light,
  primarySwatch: kPrimarySwatchColor,
  primaryColor: kPrimaryColor,
  primaryColorDark: kPrimaryDarkColor,
  primaryColorLight: kPrimaryLightColor,
  colorScheme: ColorScheme.fromSwatch(
    primarySwatch: kPrimarySwatchColor,
    accentColor: kSecondaryColor,
    backgroundColor: kBackgroundColor,
    brightness: Brightness.light,
    cardColor: kCardColor,
    errorColor: kErrorColor,
    primaryColorDark: kPrimaryDarkColor,
  ),
  fontFamily: 'Montserrat',
  textTheme: const TextTheme(
    bodyText1: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    bodyText2: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    button: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: kWhiteColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    caption: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline1: TextStyle(
      fontSize: 20,
      fontWeight: FontWeight.bold,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline2: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.w600,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline3: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline4: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline5: TextStyle(
      fontSize: 10,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    headline6: TextStyle(
      fontSize: 8,
      fontWeight: FontWeight.w500,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    subtitle1: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    subtitle2: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    overline: TextStyle(
      fontSize: 10,
      fontWeight: FontWeight.w400,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
  ),
  appBarTheme: const AppBarTheme(
    color: Colors.transparent,
    elevation: 0,
    toolbarHeight: 70,
    iconTheme: IconThemeData(
      color: kPrimaryTextColor,
    ),
    toolbarTextStyle: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
    titleTextStyle: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: kPrimaryTextColor,
      fontFamily: 'Montserrat',
      package: 'ottaa_theme',
    ),
  ),
  iconTheme: const IconThemeData(
    color: kPrimaryTextColor,
    size: 16,
  ),
);
